Version upgrade and CD master action
AOT-Technologies/formio pull request #12
Opened 2022-06-29 22:25 UTC by sumesh-aot

2022-07-15 09:19 UTC, abhilash-aot requested changes
Better avoid master. Master we are forking from Formio repo. We don't want the image as such from formio

2022-07-15 09:20 UTC, abhilash-aot reviewed
Formsflow-forms branch is added as the main default branch

2022-07-15 21:43 UTC, sumesh-aot commented
@abhilash-aot Done

2022-07-18 07:28 UTC, abilpraju-aot approved these changes

2022-07-18 07:28 UTC, abhilash-aot approved these changes

2022-07-18 07:29 UTC, merged